language: php

php:
  - 5.5.9
  - 5.6
  - 7.0
  - 7.1

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - bash <(curl -s https://codecov.io/bash)

script: phpunit
